name: plug_alerta
description: App Flutter para monitoramento de energia via MQTT
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # MQTT
  mqtt_client: ^10.0.0
  
  # UI
  cupertino_icons: ^1.0.6
  
  # Notificações
  flutter_local_notifications: ^19.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
